### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by rhaist**
From my testing those dependencies can be safely updated.
Even Elasticsearch seems to work fine after the minor version update without throwing any errors.

### CODE REVIEW

**Comment by SamuelHassine** [comment]
Hello @rhaist,

Thanks for this PR! We checked all these versions and indeed this is all good. Your PR will be merged during the next release.

**Comment by rhaist** [comment]
Elasticsearch 7.6.2 was released. I bumped the version number.
No breaking changes according to the release notes.

**Comment by SamuelHassine** [comment]
@rhaist we will release the new version today or tomorrow, could you please update your PR with ElasticSearch 7.6.2?

**Comment by rhaist** [comment]
@SamuelHassine Done.

**Pull request merged**
