### PR TITLE
OpenSearch version of composes

### LINKED ISSUE #75: New requirement: OpenSearch instead of ElasticSearch
Would it be possible to use opensearch instead of elasticsearch?
If so, could you put a corresponding docker-compose file in git.

### PR DESCRIPTION
**Pull request by leitosama**
I make some changes in `docker-compose.yml` and `docker-compose.dev.yml` to deploy OpenCTI with OpenSearch engine instead of Elastic.
It is also closes #75

### CODE REVIEW

**Comment by SamuelHassine** [comment]
Hello @leitosama,

Thanks, I think this version is useful indeed. But can you please make the change in different files and propose something like:

* docker-compose_opensearch.yml
* docker-compose_opensearch.dev.yml

**Comment by leitosama** [comment]
Hm, I would prefer to have a separate `master-opensearch` or `opensearch` branch. I think it's more Git-way of publishing various versions of deploy configs. Could you create another branch, or you insist on renaming files?

**Comment by leitosama** [comment]
@SamuelHassine any thoughts about my question?

**Comment by SamuelHassine** [comment]
Hello @leitosama,

Sorry for the late response. We will merge your PR in the "opensearch" branch and document it. Can you please solve the conflicts?

Thanks a lot!

**Comment by SamuelHassine** [comment]
Pushed in opensearch branch. Thanks!

**Pull request closed without merging**
